### ISSUE TITLE
Text fails to generate after updating the generator

### ISSUE THREAD

**Issue by petercroce** [postlight/lorem-ipsum-generator-generator#5]
Hello hello!

I was just using lorem-ipsum-generator-generator and noticed what I think is a bug. After an initial deploy, I made some changes to index.html, re-deployed, and now the generator no longer generates lorem ipsum.  

Steps to reproduce:
- Run the command to generate a generator: `npx @postlight/lorem-ipsum-generator-generator`
- Follow the instructions to add a URL (you can skip the optional steps) and select "create & configure a new site" when you get there.
- Notice that the new site generates lorem ipsum.
- Re-deploy the site by running `npm run deploy`.
- Notice the generator no longer generates lorem ipsum. In the console, you should also see a 404 for `/.netlify/functions/generate?paragraphs=4`

Maybe some small change in Netlify's serverless function deploy scripts causing the serverless function not to deploy on subsequent deploys.

**Comment by melchoyce** [comment]
Same thing happened to me — I re-deployed, and I'm getting that same console error.

**Comment by eeeps** [comment]
Just ran into I think a superset of these issues when trying to set up a new site

<details><summary>Netlify deploy failed</summary>
<pre><code>This folder isn't linked to a site yet
? What would you like to do? +  Create & configure a new site
Choose a site name or leave blank for a random name. You can update later.
? Site name (optional): landmarkov
TypeError: Cannot read property 'slug' of undefined
    at SitesCreateCommand.run (~/Repositories/aria-markov/landmarkov/node_modules/netlify-cli/src/commands/sites/create.js:42:29)
    at async SitesCreateCommand._run (~/Repositories/aria-markov/landmarkov/node_modules/netlify-cli/node_modules/@oclif/command/lib/command.js:34:20)
    at async DeployCommand.run (~/Repositories/aria-markov/landmarkov/node_modules/netlify-cli/src/commands/deploy.js:45:20)
    at async DeployCommand._run (~/Repositories/aria-markov/landmarkov/node_modules/netlify-cli/node_modules/@oclif/command/lib/command.js:34:20)
    at async Config.runCommand (~/Repositories/aria-markov/landmarkov/node_modules/netlify-cli/node_modules/@oclif/config/lib/config.js:151:9)
    at async Main.run (~/Repositories/aria-markov/landmarkov/node_modules/netlify-cli/node_modules/@oclif/command/lib/main.js:21:9)
    at async Main._run (~/Repositories/aria-markov/landmarkov/node_modules/netlify-cli/node_modules/@oclif/command/lib/command.js:34:20)</code></pre>
</details>

Tried to deploy manually with Netlify Drop and get the same 404: https://brave-jackson-cca0bc.netlify.app
